import { Droplets } from "lucide-react";
import StaticPageLayout, {
  Section,
} from "@/components/static-page/staticPageLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Environmental Policy | Industrial Wastewater Dashboard",
  description:
    "The environmental principles guiding this platform's design and use.",
};

export default function EnvironmentalPolicyPage() {
  return (
    <StaticPageLayout
      icon={Droplets}
      title="Environmental Policy"
      subtitle="Why this platform exists, and the principles behind how it's built."
    >
      <Section title="Purpose">
        <p>
          Industrial effluent treatment plants are a critical line of
          defense against water pollution, but the expertise needed to
          interpret sensor readings and translate them into corrective
          action is often scarce. This platform exists to make that
          expertise more accessible — surfacing regulatory violations early
          and pairing them with specific, actionable treatment guidance,
          rather than leaving operators with raw numbers to interpret alone.
        </p>
      </Section>

      <Section title="Responsible AI Use">
        <p>
          Recommendations generated by this platform are advisory. Chemical
          dosages, treatment processes, and maintenance actions should be
          reviewed by a qualified environmental or maintenance engineer
          before being acted on. The platform is designed to fail safely —
          when an AI service or trained model is unavailable, it falls back
          to conservative rule-based logic rather than producing an
          unreliable result silently.
        </p>
      </Section>

      <Section title="Data and Privacy">
        <p>
          Effluent and equipment readings submitted for analysis are used
          only to generate the corresponding result and are not sold or
          shared with third parties for unrelated purposes. Facility
          operators should avoid submitting personally identifiable
          information alongside sample data.
        </p>
      </Section>
    </StaticPageLayout>
  );
}
